---
- name: Install Percona XtraDB Cluster server
  apt: pkg={{ item }} 
       state=present
  with_items:
    - percona-xtradb-cluster-server-5.6
    - percona-nagios-plugins
    - python-mysqldb
    - xinetd
    - git 
